### PR TITLE
New client package

### PR DESCRIPTION
**Pull request by matt-casey**
New client library that correctly handles types from `typeof api` and works with the latest `react-query`

### CODE REVIEW

**Review by rattrayalex — COMMENTED** [review]
How can I see what it looks like to a user now?

**Review by hdemirev — COMMENTED** [review]
no issues on my end with the implementation here, curious how we can test w/ the monorepo though, is it just published to the `client-0.0.1-alpha.1` branch? or can wait for your PR if you have that in progress

**Review by meorphis — APPROVED** [review]
skimmed, lgtm

**Comment by dtmeadows** [comment]
@yjp20 / @matt-casey I was able to get tests passing here and ideally we'd get this PR merged in. Goals for this are: 
- enable renovate to run for dep updates
- keep security updates rolling

Doing so required some changes though, and a few of them are less than ideal:
- Chiefly, I couldn't get errors related to `includable` working. I've disabled this for now and ignored the tests. Ideally we'd get this working again, though it's not a feature that's being used so it's not high pri. 
- I disabled the tests in our react-query package. There's something strange going on with the bundler for testing... we can correctly run it in other packages but TS can't seem to follow the `.js` references from jest at the moment within react-query. 
- I had to tweak @yjp20's earlier change to get URI's working again: https://github.com/stainless-api/stl-api/compare/79b06858c35cb2a2498d952d8af9f99616dc37c6..ccc8298#diff-a7090a88995398f637058cefc1aeaf611ddd338943a4e2c60865a0f081b5f49f

The full diff of my changes can be [seen here](https://github.com/stainless-api/stl-api/compare/79b06858c35cb2a2498d952d8af9f99616dc37c6..ccc8298#diff-a7090a88995398f637058cefc1aeaf611ddd338943a4e2c60865a0f081b5f49f). Most of these are just dep changes though. 

Lemme know what you all think!

**Pull request merged**
